288 hide some site health issues - Closes #288
blogtutor/blog-tutor-support pull request #336
Opened 2024-06-25 19:19 UTC by CNoemi94

Hid **Persistent Object Cache and Comment Pagination**

2024-06-25 19:25 UTC, 1337rout requested changes
Just one comment about making the function a class member and using it that way :)

2024-06-25 19:25 UTC, 1337rout commented on includes/class-support-overrides.php
>  	}
Can you please move this function to inside of the class as a static public function and then call the hook in this init function? I'm making the suggestion in github so linting and whitespace may not be perfect. Please don't use the commit suggestion feature and instead manually commit this after testing on your local. 
```suggestion
		add_filter( 'site_status_tests', array( $this, 'remove_site_health_test', 99 ) );
	}
			public static function remove_site_health_test( $tests ) {
			unset( $tests['direct']['persistent_object_cache'], $tests['direct']['yoast-page-comments-check'] );
			return $tests;
		}
```

2024-06-25 19:48 UTC, 1337rout approved these changes
LGTM! Thanks for updating it. :sunglasses:

2024-07-18 23:21 UTC, blogtutor commented
Looks good, tested on dev.nerdpress.net.  

Before:

![image](https://github.com/user-attachments/assets/357498d3-42b0-4c6f-9c79-7002c6b1ed80)

After:

![image](https://github.com/user-attachments/assets/debbb961-ec3f-4f22-84eb-f33120f76c3b)

2024-07-18 23:22 UTC, merged